In [2]:
import numpy as np
import sys
import polars as pl
import pandas as pd
import random
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from imblearn.under_sampling import NearMiss
from sklearn import metrics
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, confusion_matrix, precision_recall_curve
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score

In [20]:
data = (pl.read_csv('../results/results/embeddings/rag_ember-v1_gpt4_embeddings.csv', # has_header=False,
                    new_columns=['condition_name', 'drug_name', 'affect'])
        .filter(pl.col('affect') != 0)
        .with_columns(
            pl.when(pl.col('affect') == 1).then(1).otherwise(0).alias("affect")
            )
        )
print(data.shape)
data.head()

(1476, 2051)


shape: (5, 2_051)
┌────────────┬────────────┬────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ condition_ ┆ drug_name  ┆ affect ┆ 0         ┆ … ┆ 1020_dupl ┆ 1021_dupl ┆ 1022_dupl ┆ 1023_dupl │
│ name       ┆ ---        ┆ ---    ┆ ---       ┆   ┆ icated_0  ┆ icated_0  ┆ icated_0  ┆ icated_0  │
│ ---        ┆ str        ┆ i32    ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆            ┆        ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ acute      ┆ 6-aminocap ┆ 0      ┆ -0.113791 ┆ … ┆ -0.554994 ┆ -0.122884 ┆ -0.441791 ┆ -0.550147 │
│ kidney     ┆ roic acid  ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ injury     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ acute      ┆ 3-iodobenz ┆ 0      ┆ 0.167238  ┆ … ┆ -0.479792 ┆ 0.089264  ┆ -0.3088   ┆ -0.232126 │
│ kidney     ┆ ylguanidin ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ injury     ┆ e          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ acute      ┆ abacavir   ┆ 0      ┆ -0.950485 ┆ … ┆ -0.724895 ┆ 0.161244  ┆ 0.193736  ┆ -0.699643 │
│ kidney     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ injury     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ acute      ┆ abatacept  ┆ 0      ┆ -0.644795 ┆ … ┆ -0.35752  ┆ 0.140006  ┆ -0.479819 ┆ -0.665837 │
│ kidney     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ injury     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ acute      ┆ abemacicli ┆ 0      ┆ -0.321315 ┆ … ┆ -0.311689 ┆ -0.368671 ┆ 0.032888  ┆ -0.406301 │
│ kidney     ┆ b          ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
│ injury     ┆            ┆        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [21]:
data['condition_name'].value_counts().sort(by = 'condition_name')

shape: (4, 2)
┌─────────────────────────────┬───────┐
│ condition_name              ┆ count │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ acute kidney injury         ┆ 425   │
│ acute liver injury          ┆ 512   │
│ acute myocardial infarction ┆ 313   │
│ gi bleed                    ┆ 226   │
└─────────────────────────────┴───────┘

In [22]:
embed_col_names = [x for x in data.columns if x not in ['condition_name', 'drug_name', 'affect', 'outcome', 'status', '']]
support_cols = [x for x in embed_col_names if 'duplicated' not in x]
refute_cols = [x for x in embed_col_names if 'duplicated' in x]

In [23]:
data['affect'].value_counts()

shape: (2, 2)
┌────────┬───────┐
│ affect ┆ count │
│ ---    ┆ ---   │
│ i32    ┆ u32   │
╞════════╪═══════╡
│ 1      ┆ 139   │
│ 0      ┆ 1337  │
└────────┴───────┘

In [24]:
condition = 'acute kidney injury'

In [26]:
def make_classifier(model):
    if model == 'logistic':
        clf = LogisticRegression(random_state=0)
    if model == 'rf':
        clf = RandomForestClassifier(random_state=0)
    if model == 'knn':
        clf = KNeighborsClassifier(n_neighbors=5, random_state=0)
    return clf

## Cross Validation

In [ ]:
def get_cross_vals(X,y, ):


In [25]:
print(cross_val_score(clf, X_actual, y_actual, cv=5, scoring = 'roc_auc'))
print(cross_val_score(clf, X_actual, y_actual, cv=5, scoring = 'average_precision'))

NameError: name 'clf' is not defined

## Undersampling

In [85]:
random.seed(100)
y_actual = data['affect'].to_numpy()
X_actual = data[embed_col_names].to_numpy()
undersample = NearMiss(version=1, n_neighbors=5)
X,y = undersample.fit_resample(X_actual, y_actual)

In [86]:
# train on other data - train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=100, stratify=y)

In [87]:
clf = LogisticRegression(random_state=0)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
predict_probs = clf.predict_proba(X_test)

In [89]:
precision, recall, thresholds = precision_recall_curve(y_test, predict_probs[:,1])
f1_scores = 2*recall*precision/(recall+precision)
print('Best threshold: ', thresholds[np.argmax(f1_scores)])
print('Best F1-Score: ', np.max(f1_scores))

Best threshold:  0.8467536368462844
Best F1-Score:  0.9117647058823528


In [90]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[31  4]
 [ 3 31]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90        35
           1       0.89      0.91      0.90        34

    accuracy                           0.90        69
   macro avg       0.90      0.90      0.90        69
weighted avg       0.90      0.90      0.90        69



In [97]:
print(cross_val_score(clf, X_actual, y_actual, cv=5, scoring = 'roc_auc'))
print(cross_val_score(clf, X_actual, y_actual, cv=5, scoring = 'average_precision'))

[0.88736871 0.82324489 0.76457999 0.79454254 0.88242376]
[0.53185648 0.3257435  0.30931476 0.42108849 0.56033103]


In [63]:
predictions = clf.predict(X_actual)
print(confusion_matrix(y_actual, predictions))
print(f1_score(y_actual, predictions))

[[537 800]
 [  3 135]]
0.2516309412861137


In [91]:

X_train, X_test, y_train, y_test = train_test_split(X_actual, y_actual, test_size=0.3, random_state=100, stratify=y_actual)

In [92]:
clf = LogisticRegression(random_state=0,    max_iter=1000) #, class_weight='balanced')
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
predict_proba = clf.predict_proba(X_test)
print(confusion_matrix(y_test, predictions))
print(f1_score(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[385  17]
 [ 24  17]]
0.4533333333333333
0.90744920993228


In [72]:
precision, recall, thresholds = precision_recall_curve(y_test, predict_proba[:,1])
f1_scores = 2*recall*precision/(recall+precision)
print('Best threshold: ', thresholds[np.argmax(f1_scores)])
print('Best F1-Score: ', np.max(f1_scores))

Best threshold:  0.4159840383391849
Best F1-Score:  0.5227272727272727
